### ISSUE TITLE
Old version cryptography

### ISSUE THREAD

**Issue by dave2309** [regisb/slack-cli#18]
Hi,

On every action I got that
`.local/lib/python2.7/site-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)`

Anything I can try for that?

Thanks

**Comment by regisb** [comment]
Hi @dave2309! This warning is printed by `requests`. Here is the corresponding commit: https://github.com/kennethreitz/requests/commit/15054aa3909da2383e8cfa9abcd296ba46a7200f
I see that the minimal required version to avoid this warning is cryptography==1.3.4. Maybe you can try to upgrade the cryptorgraphy package with:

    pip install -U --user cryptography

**Comment by dave2309** [comment]
Thanks,
I just tried that, It upgraded but then
`$ slack-cli 
Traceback (most recent call last):
  File "/home/.local/bin/slack-cli", line 7, in <module>
    from slackcli.cli import main
  File "/home/.local/lib/python2.7/site-packages/slackcli/cli.py", line 11, in <module>
    from . import slack
  File "/home/.local/lib/python2.7/site-packages/slackcli/slack.py", line 1, in <module>
    import slacker
  File "/home/.local/lib/python2.7/site-packages/slacker/__init__.py", line 17, in <module>
    import requests
  File "/home/.local/lib/python2.7/site-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/home/.local/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
`

**Comment by dave2309** [comment]
I needed to uninstall ubuntu package `apt remove python-openssl`
And then install `pip install --user pyOpenSSL`
Seems to be working better now,
Thanks for support

**Comment by regisb** [comment]
:+1:
