### ISSUE TITLE
"slacker.Error: method_not_supported_for_channel_type"

### ISSUE THREAD

**Issue by dave2309** [regisb/slack-cli#19]
Sorry for another issue but listening to "all" channel gives me this
```
$ slack-cli -T team -s all

Traceback (most recent call last):
  File "/home/david.tourrel/.local/bin/slack-cli", line 11, in <module>
    sys.exit(main())
  File "/home/david.tourrel/.local/lib/python2.7/site-packages/slackcli/cli.py", line 27, in main
    sys.exit(run())
  File "/home/david.tourrel/.local/lib/python2.7/site-packages/slackcli/cli.py", line 94, in run
    stream.receive(args.src)
  File "/home/david.tourrel/.local/lib/python2.7/site-packages/slackcli/stream.py", line 11, in receive
    loop(sources)
  File "/local/lib/python2.7/site-packages/slackcli/stream.py", line 31, in loop
    source_name = names.sourcename(data['channel'])
  File "/local/lib/python2.7/site-packages/slackcli/names.py", line 78, in sourcename
    return SourceIndex.instance().name(user_id)
  File "/local/lib/python2.7/site-packages/slackcli/names.py", line 70, in name
    self.source_index[source_id] = slack.client().channels.info(source_id).body['channel']['name']
  File "/local/lib/python2.7/site-packages/slacker/__init__.py", line 292, in info
    return self.get('channels.info', params={'channel': channel})
  File "/.local/lib/python2.7/site-packages/slacker/__init__.py", line 117, in get
    api, **kwargs
  File "/.local/lib/python2.7/site-packages/slacker/__init__.py", line 99, in _request
    raise Error(response.error)
slacker.Error: method_not_supported_for_channel_type
```
Is there anything I can do?
Thanks

**Comment by dave2309** [comment]
Actually any channel or user gives the same error

**Comment by regisb** [comment]
Can you try `slack-cli -s general -l 100`?

**Comment by dave2309** [comment]
That does work. But, of course, not like a stream...

**Comment by regisb** [comment]
What about `slack-cli -s general`?

**Comment by dave2309** [comment]
Ok to be fair, `slack-cli -s all` (or any others) seems to work... for about 10 minutes, then crashes with the error I mentioned.

**Comment by regisb** [comment]
That's an important information :) does it crash on a bot's message?

**Comment by regisb** [comment]
I think the problem comes from messages posted in private groups. Please upgrade to the latest version (v2.2.4). Feel free to re-open if you observe the same problem.
