### ISSUE TITLE
Unicode Decode Error on pip install - Windows 10

### ISSUE THREAD

**Issue by harbertc** [regisb/slack-cli#20]
When running the pip install on Windows 10, I get the following...

```
pip install slack-cli
Collecting slack-cli
  Using cached https://files.pythonhosted.org/packages/fe/76/4d2500060ee50297f776eec354b1f2925fb42e454991dec004650f677dff/slack-cli-2.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\CHRISH~1\AppData\Local\Temp\pip-install-udsgp7nr\slack-cli\setup.py", line 16, in <module>
        long_description=(read('README.rst')),
      File "C:\Users\CHRISH~1\AppData\Local\Temp\pip-install-udsgp7nr\slack-cli\setup.py", line 10, in read
        return filename.read()
      File "c:\python36\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 4779: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\CHRISH~1\AppData\Local\Temp\pip-install-udsgp7nr\slack-cli\
```

**Comment by regisb** [comment]
Hi @harbertc,
Thanks for the report! I made an attempt at fixing this in v2.2.5. Can you please confirm if it works by running `pip install slack-cli` again?

**Comment by harbertc** [comment]
Worked great. What an amazingly fast turnaround. Thanks, @regisb!
