### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character, ordinal not in range(128)

### ISSUE THREAD

**Issue by Arthaey** [regisb/slack-cli#24]
I ran `pip install slack-cli` on my Mac. Worked fine, was able to send myself a test DM. Awesome!

But then I tried to download messages from a channel and got this error:

```
> slack-cli --token $TOKEN --last 10000 --src my-public-channel > channel.log
Traceback (most recent call last):
  File "/usr/local/bin/slack-cli", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/slackcli/cli.py", line 27, in main
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/slackcli/cli.py", line 99, in run
    last_messages(args.src, args.last)
  File "/usr/local/lib/python2.7/site-packages/slackcli/cli.py", line 141, in last_messages
    utils.print_messages(source, count=count)
  File "/usr/local/lib/python2.7/site-packages/slackcli/utils.py", line 63, in print_messages
    print(format_message(source_name, message))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2192' in position 120: ordinal not in range(128)
```

**Comment by regisb** [comment]
Haaaaa the joys of unicodes in python 2.7... Do you have python 3 on your laptop? Can you please try to install slack-cli with python 3 instead? You can probably do so by running `pip3 install slack-cli`.
