### ISSUE TITLE
Error DistributionNotFound

### ISSUE THREAD

**Issue by Peitemoukiemena** [regisb/slack-cli#33]
```
 slack-cli -h
Traceback (most recent call last):
  File "/bin/slack-cli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: configparser>=3.5
```

I installed the latest version with pip and running any slack-cli command returns this error. What are the requirements?

My system, Centos 7
```
Python 2.7.5
pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
```
Do I need other versions?

**Comment by regisb** [comment]
Hi @Peitemoukiemena! slack-cli is no longer compatible with python 2.7. Please upgrade to python 3.5+.
