### ISSUE TITLE
Auth requests a token with dnd.info despite dnd:read being granted

### ISSUE THREAD

**Issue by yetyetanotherusername** [regisb/slack-cli#38]
I tried setting up slack-cli and set all scopes for the token like shown in the readme, however slack-cli rejects the token saying that `This token requires the 'dnd:info' scope.` I had a look in slacks API documentation and the method `dnd.info` has apparently been deprecated. This effectively locks me out of authenticating.

**Comment by regisb** [comment]
Hi @yetyetanotherusername! Where did you see that the dnd:info scope is deprecated? It is still documented here: https://api.slack.com/methods/dnd.info

**Comment by yetyetanotherusername** [comment]
Oof, you're right, I misread the documentation, sorry :-/. I still can't figure out how to add the dnd:info scope. I tried adding dnd:write but it doesn't change anything.

**Comment by regisb** [comment]
The new way to create Slack applications makes interacting with the Slack API more complex for all users... I need to figure out a way to automatically create a slack app with the right scopes, and that does not need administrator approval to install the app in the workspace.

**Comment by azurelysium** [comment]
Hi, I have had the same problem.
The solution was to add the OAuth scope `team:read`

The code below made an exception due to the missing scope.
The error message said that `dnd:info` was missing. I think `dnd:info` could be replaced with `team:read``

```
# Get team
try:
    team = team or client().team.info().body["team"]["domain"]
...
```

**Comment by regisb** [comment]
@azurelysium I trust you. I made the change in v2.2.9.

**Comment by yetyetanotherusername** [comment]
Ok, this did something. 

On trying to authenticate, the slack-cli crashes with the following stack:
```
Traceback (most recent call last):
  File "/home/sgrill/Documents/repos/slack/.env/bin/slack-cli", line 11, in <module>
    load_entry_point('slack-cli==2.2.9', 'console_scripts', 'slack-cli')()
  File "/home/sgrill/Documents/repos/slack/.env/lib64/python3.8/site-packages/slackcli/cli.py", line 27, in main
    sys.exit(run())
  File "/home/sgrill/Documents/repos/slack/.env/lib64/python3.8/site-packages/slackcli/cli.py", line 115, in run
    stream.receive(args.src)
  File "/home/sgrill/Documents/repos/slack/.env/lib64/python3.8/site-packages/slackcli/stream.py", line 11, in receive
    loop(sources)
  File "/home/sgrill/Documents/repos/slack/.env/lib64/python3.8/site-packages/slackcli/stream.py", line 17, in loop
    url = slack.client().rtm.start().body["url"]
  File "/home/sgrill/Documents/repos/slack/.env/lib64/python3.8/site-packages/slacker/__init__.py", line 679, in start
    return self.get('rtm.start',
  File "/home/sgrill/Documents/repos/slack/.env/lib64/python3.8/site-packages/slacker/__init__.py", line 115, in get
    return self._request(
  File "/home/sgrill/Documents/repos/slack/.env/lib64/python3.8/site-packages/slacker/__init__.py", line 99, in _request
    raise Error(response.error)
slacker.Error: missing_scope
```
output of pip freeze:
```
appdirs==1.4.4
argcomplete==1.11.1
certifi==2020.4.5.1
chardet==3.0.4
idna==2.9
requests==2.23.0
six==1.15.0
slack-cli==2.2.9
slacker==0.11.0
urllib3==1.25.9
websocket-client==0.54.0
```
Scopes:
![image](https://user-images.githubusercontent.com/15213889/82643490-e04ff380-9c0f-11ea-8bd9-44e1ef0e5e9c.png)

**Comment by azurelysium** [comment]
@yetyetanotherusername 

In this document, https://api.slack.com/rtm
```
New Slack apps may not use any Real Time Messaging API method. Create a classic app and use the V1 Oauth flow to use RTM.New Slack apps may not use any Real Time Messaging API method. Create a classic app and use the V1 Oauthflow to use RTM.
```

The latest Slack App's OAuth scope list does not include `rtm.start` or other Real Time Messaging scopes. I have tried to create a classic Slack app but gave up to make authorization work. I guess that you can receive and send Slack messages except streaming incoming messages.

**Comment by yetyetanotherusername** [comment]
I see, thanks for your help. Pretty lame move by slack. :-/

**Comment by tjg37** [comment]
I was also receiving the same error `This token requires the 'dnd:info' scope` when initially adding a token. 

I followed the advice above and added the OAuth scope `team:read`, then when I tried to send a message, I got the following error:

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/django-adaptor-36/bin/slack-cli", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/django-adaptor-36/lib/python3.6/site-packages/slackcli/cli.py", line 27, in main
    sys.exit(run())
  File "/opt/anaconda3/envs/django-adaptor-36/lib/python3.6/site-packages/slackcli/cli.py", line 144, in run
    send_message(args.dst, message, pre=args.pre, username=args.user)
  File "/opt/anaconda3/envs/django-adaptor-36/lib/python3.6/site-packages/slackcli/cli.py", line 191, in send_message
    destination_id = utils.get_destination_id(destination)
  File "/opt/anaconda3/envs/django-adaptor-36/lib/python3.6/site-packages/slackcli/utils.py", line 13, in get_destination_id
    return get_resource(name)[1]["id"]
  File "/opt/anaconda3/envs/django-adaptor-36/lib/python3.6/site-packages/slackcli/utils.py", line 17, in get_resource
    for resource_type, resource in iter_resources():
  File "/opt/anaconda3/envs/django-adaptor-36/lib/python3.6/site-packages/slackcli/utils.py", line 34, in iter_resources
    for resource in fetcher():
  File "/opt/anaconda3/envs/django-adaptor-36/lib/python3.6/site-packages/slackcli/utils.py", line 29, in <lambda>
    ("channel", lambda: slack.client().channels.list().body["channels"]),
  File "/opt/anaconda3/envs/django-adaptor-36/lib/python3.6/site-packages/slacker/__init__.py", line 297, in list
    'exclude_members': exclude_members})
  File "/opt/anaconda3/envs/django-adaptor-36/lib/python3.6/site-packages/slacker/__init__.py", line 117, in get
    api, **kwargs
  File "/opt/anaconda3/envs/django-adaptor-36/lib/python3.6/site-packages/slacker/__init__.py", line 99, in _request
    raise Error(response.error)
slacker.Error: method_deprecated
```

This appears to be related to https://github.com/regisb/slack-cli/issues/40.
